[package]
name = "proxmox-backup-qemu"
version = "0.1.0"
authors = [
    "Dietmar Maurer <dietmar@proxmox.com>",
    "Wolfgang Bumiller <w.bumiller@proxmox.com>",
]
edition = "2018"
build = "build.rs"

[lib]
crate-type = ['lib', 'cdylib', 'staticlib']

[build-dependencies]
cbindgen = "0.13.1"

[dependencies]
libc = "0.2"
bytes = "0.5"
proxmox = { version = "0.1.13", features = [ "sortable-macro", "api-macro" ] }
proxmox-backup = { path = "../proxmox-backup" }
chrono = "0.4" # Date and time library for Rust
failure = "0.1"
futures = "0.3"
serde_json = "1.0"
tokio = { version = "0.2.9", features = [ "blocking", "fs", "io-util", "macros", "rt-threaded", "signal", "stream", "tcp", "time", "uds" ] }
openssl = "0.10"
h2 = { version = "0.2", features = ["stream"] }

