[package]
name = "proxmox-backup-qemu"
version = "0.1.0"
authors = [
    "Dietmar Maurer <dietmar@proxmox.com>",
    "Wolfgang Bumiller <w.bumiller@proxmox.com>",
]
edition = "2018"
build = "build.rs"

[lib]
crate-type = ['lib', 'cdylib', 'staticlib']

[build-dependencies]
cbindgen = "0.9.1"

[dependencies]
libc = "0.2"
bytes = "0.4"
proxmox = { git = "ssh://gitolite3@proxdev.maurer-it.com/rust/proxmox", version = "0.1" }
proxmox-backup = { path = "../proxmox-backup" }
chrono = "0.4" # Date and time library for Rust
failure = "0.1"
futures-preview = "0.3.0-alpha"
serde_json = "1.0"
tokio = { version = "0.2.0-alpha.4" }
openssl = "0.10"

